management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  info:
    java:
      enabled: true
    os:
      enabled: true
  health:
    diskspace:
      enabled: true
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
    info:
      enabled: true

# Logging config
logging:
  pattern:
    console: "%-5level: %class{0} - %msg%n"
  level:
    root: INFO
    org.springframework.boot: DEBUG
    org.springframework: DEBUG
    com.apache.brooklyn.example: INFO
    org.hibernate: DEBUG

server:
  port: 8080

spring:
  application:
    name: brooklyn
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_IP:localhost}:${DB_PORT:3306}/visitors?useSSL=false
    username: ${DB_USER:brooklyn}
    password: ${DB_PASS:br00k11n}
    hikari:
      maximum-pool-size: 25
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        jdbc:
          batch_size: 10
          fetch_size: 30
        max_fetch_depth: 3
        show-sql: true
        format-sql: false
        use_sql_comments: false
