
# Logging config
logging:
  pattern:
    console: "%-5level: %class{0} - %msg%n"
  level:
    root: INFO
    org.springframework.boot: INFO
    com.apache.brooklyn.example: INFO

server:
  port: 8080

spring:
  application:
    name: brooklyn
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:./visitors;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: admin
    hikari:
      maximum-pool-size: 25
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          batch_size: 10
          fetch_size: 30
        max_fetch_depth: 3
        show-sql: true
        format-sql: false
        use_sql_comments: false
